### PR TITLE
Explicit UTF-8 encoding in app config

### PR DESCRIPTION
**Pull request by karkar**

### CODE REVIEW

**Comment by jayfo** [comment]
Good catch.

Are there more `open( )` around that we should be doing this to?

Was there content in these files that prompted this?  We agree that content should be there, it's not just dumb smart quotes or something like that?

**Comment by karkar** [comment]
Using a ' or - was leading to some weird ascii characters. I knew it was happening for some quotes and ran into it while naming the worksheets yesterday.

**Comment by jayfo** [comment]
Those are both ASCII though, shouldn't have caused issues?

**Comment by jayfo** [comment]
Ravi and I agree via Slack.

**Pull request merged**
