### PR TITLE
Jinasuh/v0.3.0 registry bugs

### PR DESCRIPTION
**Pull request by jinasuh**
Several bug fixes to the registry. See associated issues.

### CODE REVIEW

**Comment by karkar** [comment]
@jayfo the fix to #290 is a schema addition. Adding 'billable minutes' to the case review form. Raising this to you in case you wanted to test any small schema updates.

**Comment by karkar** [comment]
My simulator seems to be having some page cropping issue in activity progress. 
image

**Comment by karkar** [comment]
@jinasuh I noticed a related issue in activity tracking and have raised a new issue for it. Sharing it here for awareness in case you go back in to fix activities. https://github.com/uwscope/scope-web/issues/305

**Comment by karkar** [comment]
Sharing my test notes for this PR:

- Allow multiline comment in tables #297

- Widen reco column #298

- Rename Values Inventory to Values & Activities Inventory #300
- 
- Add billable minutes to case review in registry #290
- 
- Fix activity tracking #288 #287
-

**Comment by jinasuh** [comment]
Breaking this into two branches (and PRs).

**Pull request closed without merging**
