### PR TITLE
Fixes to registry tables, activity tracking, and values inventory title

### PR DESCRIPTION
**Pull request by jinasuh**
- Fix activity tracking detail in registry and patient app #288 #287 
- Rename Values Inventory to Values & Activities Inventory #300
- Widen recommendation column in registry session table #298
- Allow multiline comment in tables #297

### CODE REVIEW

**Comment by jinasuh** [comment]
@karkar This PR includes everything from PR #304 as well as few issues you raised there (word break + alt activity) except schema change.

**Comment by jayfo** [comment]
Reviewed 9e8e3030d428c3c1fa238d4144c35380e573d024 for #297
Reviewed 84b6d02c9557465702a08d0b8e5f4304093c3435 for #298
Reviewed aef4cded347a9a673fb45a3a87067a8c0c07008f for #300

**Comment by jayfo** [comment]
@karkar : You made a comment here regarding #288:

https://github.com/uwscope/scope-web/issues/288#issuecomment-1092282418

Suggested we may need to fix old records. Is that being tracked in a separate issue?

**Comment by jayfo** [comment]
@karkar : This includes a fix for word breaking in table data that you called out here:

https://github.com/uwscope/scope-web/pull/304#issuecomment-1101515095

But there's no corresponding issue, Jina fixed based on your comment in that PR, fix is 88b5b86c4f120e0b959b983da39bd08a3ae5f623.

Can you open an issue, we'll update this PR to fix that issue?

**Review by jayfo — APPROVED** [review]
Code looks code.  Opened a question for @karkar , need an issue for 88b5b86c4f120e0b959b983da39bd08a3ae5f623

**Review by karkar — APPROVED** [review]
Confirming that the registry changes are working and the issue in the previous PR with text getting cropped in patient app is also not showing up (https://github.com/uwscope/scope-web/pull/308#issuecomment-1116084757)

**Comment by karkar** [comment]
> Reviewed [9e8e303](https://github.com/uwscope/scope-web/commit/9e8e3030d428c3c1fa238d4144c35380e573d024) for #297 Reviewed [84b6d02](https://github.com/uwscope/scope-web/commit/84b6d02c9557465702a08d0b8e5f4304093c3435) for #298 Reviewed [aef4cde](https://github.com/uwscope/scope-web/commit/aef4cded347a9a673fb45a3a87067a8c0c07008f) for #300 Reviewed [ed47c24](https://github.com/uwscope/scope-web/commit/ed47c24e494af586c02b3646846260870af9319a) for #287 #288 Reviewed [88b5b86](https://github.com/uwscope/scope-web/commit/88b5b86c4f120e0b959b983da39bd08a3ae5f623), asked Ravi to create issue for what it fixes Reviewed [fc37f62](https://github.com/uwscope/scope-web/commit/fc37f629dec7cea59f3d3f0028668ee02321e1e6) for #305

https://github.com/uwscope/scope-web/issues/316

**Pull request merged**
